<!doctype html><html lang=en dir=auto><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name=robots content="index, follow"><title>Exception Translation | Well Organized Bits</title><meta name=keywords content><meta name=description content="Can a typical &ldquo;Internal Server Error&rdquo; be improved a bit? Let&rsquo;s find out.
In fact, let&rsquo;s consider more than just a response that is typically associated with internal server errors. Those types of errors usually originate in the outermost try/catch expression. There we might find code to:
respond with HTTP status code 500 increment a metric that an unknown exception occurred log the event 1 save the exception to the database 2 etc."><meta name=author content="Miro Bezjak"><link rel=canonical href=https://mbezjak.github.io/posts/exception-translation/><meta name=google-site-verification content="62Vyu3hWVePJQe8DUK8iM3Xn2VdjXAAagXEIxsL5To0"><link crossorigin=anonymous href=/assets/css/stylesheet.bc1149f4a72aa4858d3a9f71462f75e5884ffe8073ea9d6d5761d5663d651e20.css integrity="sha256-vBFJ9KcqpIWNOp9xRi915YhP/oBz6p1tV2HVZj1lHiA=" rel="preload stylesheet" as=style><script defer crossorigin=anonymous src=/assets/js/highlight.f413e19d0714851f6474e7ee9632408e58ac146fbdbe62747134bea2fa3415e0.js integrity="sha256-9BPhnQcUhR9kdOfuljJAjlisFG+9vmJ0cTS+ovo0FeA=" onload=hljs.initHighlightingOnLoad()></script>
<link rel=icon href=https://mbezjak.github.io/favicon.ico><link rel=icon type=image/png sizes=16x16 href=https://mbezjak.github.io/favicon-16x16.png><link rel=icon type=image/png sizes=32x32 href=https://mbezjak.github.io/favicon-32x32.png><link rel=apple-touch-icon href=https://mbezjak.github.io/apple-touch-icon.png><link rel=mask-icon href=https://mbezjak.github.io/safari-pinned-tab.svg><meta name=theme-color content="#2e2e33"><meta name=msapplication-TileColor content="#2e2e33"><noscript><style>#theme-toggle,.top-link{display:none}</style><style>@media(prefers-color-scheme:dark){:root{--theme:rgb(29, 30, 32);--entry:rgb(46, 46, 51);--primary:rgb(218, 218, 219);--secondary:rgb(155, 156, 157);--tertiary:rgb(65, 66, 68);--content:rgb(196, 196, 197);--hljs-bg:rgb(46, 46, 51);--code-bg:rgb(55, 56, 62);--border:rgb(51, 51, 51)}.list{background:var(--theme)}.list:not(.dark)::-webkit-scrollbar-track{background:0 0}.list:not(.dark)::-webkit-scrollbar-thumb{border-color:var(--theme)}}</style></noscript><meta property="og:title" content="Exception Translation"><meta property="og:description" content="Can a typical &ldquo;Internal Server Error&rdquo; be improved a bit? Let&rsquo;s find out.
In fact, let&rsquo;s consider more than just a response that is typically associated with internal server errors. Those types of errors usually originate in the outermost try/catch expression. There we might find code to:
respond with HTTP status code 500 increment a metric that an unknown exception occurred log the event 1 save the exception to the database 2 etc."><meta property="og:type" content="article"><meta property="og:url" content="https://mbezjak.github.io/posts/exception-translation/"><meta property="article:section" content="posts"><meta property="article:published_time" content="2023-02-10T12:01:31+01:00"><meta property="article:modified_time" content="2023-02-10T12:01:31+01:00"><meta name=twitter:card content="summary"><meta name=twitter:title content="Exception Translation"><meta name=twitter:description content="Can a typical &ldquo;Internal Server Error&rdquo; be improved a bit? Let&rsquo;s find out.
In fact, let&rsquo;s consider more than just a response that is typically associated with internal server errors. Those types of errors usually originate in the outermost try/catch expression. There we might find code to:
respond with HTTP status code 500 increment a metric that an unknown exception occurred log the event 1 save the exception to the database 2 etc."><script type=application/ld+json>{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":2,"name":"Posts","item":"https://mbezjak.github.io/posts/"},{"@type":"ListItem","position":3,"name":"Exception Translation","item":"https://mbezjak.github.io/posts/exception-translation/"}]}</script><script type=application/ld+json>{"@context":"https://schema.org","@type":"BlogPosting","headline":"Exception Translation","name":"Exception Translation","description":"Can a typical \u0026ldquo;Internal Server Error\u0026rdquo; be improved a bit? Let\u0026rsquo;s find out.\nIn fact, let\u0026rsquo;s consider more than just a response that is typically associated with internal server errors. Those types of errors usually originate in the outermost try/catch expression. There we might find code to:\nrespond with HTTP status code 500 increment a metric that an unknown exception occurred log the event 1 save the exception to the database 2 etc.","keywords":[],"articleBody":"Can a typical “Internal Server Error” be improved a bit? Let’s find out.\nIn fact, let’s consider more than just a response that is typically associated with internal server errors. Those types of errors usually originate in the outermost try/catch expression. There we might find code to:\nrespond with HTTP status code 500 increment a metric that an unknown exception occurred log the event 1 save the exception to the database 2 etc. We’ll try to improve everything in the catch block. Just by a little bit.\nIt might be a bit easier if we have an example of what we’ll target for improvement. Here it is.\n(defn wrap-exception [handler] (fn [request] (try (handler request) (catch Exception ex (increment-metric-unknown-exception) (log-unknown-exception ex request) (save-to-db ex request) (respond-with-http-500))))) The code above is an example of a ring middleware. It doesn’t have to be ring, or even HTTP service specific. Any outermost try/catch expression is relevant for this post:\nwhen using java.util.concurrent.ExecutorService, or spawning new threads in general, or using java.lang.Thread.UncaughtExceptionHandler, or a try/catch in -main for command line applications, etc. What is there to improve? The outermost try/catch expression is all about handling an unknown exception. That is completely fine. After all, it’s not possible to anticipate and/or handle every unforeseen situation.\nHowever, the way the catch block is usually implemented does have some drawbacks. At the same time, it’s both eliminating too much information and not accumulating enough information.\nResponding with HTTP 500 is usually collapsing a rich source of information (stack trace, exception message, any other data the exception is carrying) into a single error message “Something went wrong”. That’s perhaps too much reduction of information. There is a lot of middle ground between responding with a complete stack trace and responding with a generic error message. On the other hand, simply dumping all that information as an unknown exception log event, saving it to DB, or incrementing the same metric is not ideal. That groups too much into a single category making it harder to deal with. Extracting a bit more information about the exception might help with categorization. The above is still a bit too abstract. Let’s see how those problems might manifest in the real world: losing users’ confidence and/or wasting time. What happens when internal server errors happen a bit too often?\nHow would you feel if you saw “Internal Server Error” too frequently in an app you need to use? Apart from “something didn’t work”, the error doesn’t tell you much. You’d probably be a bit annoyed. Then you’d start questioning if the last thing you did was saved successfully or not. The same thing can happen to any user of your service: a paying customer, an employee (for internal apps), a member of the QA team, or other developers if they are consuming your service. They all can become disheartened because they don’t have the necessary information to conclude something about the error. Is it a real bug or simply something transient?\nIf you’re lucky, someone might report a generic error they saw while using the app. That issue needs to be groomed, planned, and eventually, someone in the development team needs to spend time debugging it. If the end result is “That was just a DB lock timeout. They should have tried again.” then a lot of people wasted a bunch of time for no good reason. In fact, to “save time”, someone might try to shoot down similar issues early on (e.g. in grooming) without doing the investigation to confirm their assumption. Are you sure that’s not a real bug that was just ignored?\nEven if no new issues enter the Backlog, there is a similar waste happening when viewing the logs for recent unknown exceptions. Are you mentally filtering out the “I’ve seen those exceptions already multiple times” from the list of all logged unknown exceptions? Or maybe you don’t feel like looking at the list anymore because it’s mostly stuff you’ve seen before.\nThis is what we want to avoid. We want the metrics, logs, and errors that the users see to be a bit more relevant so that when the actual bugs happen, everyone sees them clearly.\nException examples Let’s see a couple of exceptions that might end up being caught in the outermost try/catch expression. If you have access to the production logs, you could also extract the exception from the last 7 days and consider them as well.\njava.lang.NullPointerException java.lang.IllegalArgumentException java.lang.ClassCastException: class java.lang.Long cannot be cast to class clojure.lang.IFn java.net.SocketException: Network is unreachable java.net.SocketTimeoutException: Connect timed out java.net.SocketTimeoutException: Read timed out java.net.ConnectException: Connection refused java.net.UnknownHostException: external-service.com: Name or service not known java.io.FileNotFoundException: /external-service/file-to-import.json (No such file or directory) java.io.FileNotFoundException: /external-service/file-to-import.json (Permission denied) java.io.IOException: Attempted read on closed stream. java.io.IOException: Read error org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout org.postgresql.util.PSQLException: ERROR: canceling statement due to lock timeout Where: while updating tuple (0,1) in relation \"users\" org.postgresql.util.PSQLException: ERROR: deadlock detected Detail: Process 186 waits for ShareLock on transaction 1140; blocked by process 196. Process 196 waits for ShareLock on transaction 1139; blocked by process 186. Hint: See server log for query details. Where: while updating tuple (0,1) in relation \"users\" org.postgresql.util.PSQLException: ERROR: new row for relation \"users\" violates check constraint \"users_email_check\" Detail: Failing row contains (...). org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint \"users_pkey\" Detail: Key (id)=(...) already exists. org.postgresql.util.PSQLException: FATAL: sorry, too many clients already org.postgresql.util.PSQLException: Ran out of memory retrieving query results. etc. Are those exceptions all the same? Should they all be handled as unknown exceptions? Let’s reason through a couple of examples and ask ourselves two questions:\nHow unexpected is this exception? How frequently do we expect it to occur? Answering the questions above:\nExceptions 1. - 3. and 11. are usually completely unexpected. They represent a bug in the system. Perhaps a missing validation if not an actual defect. They should not occur frequently. Best if they don’t occur at all. Exceptions 4. - 8. might happen if the network becomes unreliable for some reason. Perhaps someone updated or is currently updating the cloud infrastructure? How often does someone break the development (or other) environment in your team? Exceptions 9. and 10.: in the old days, files were shared via FTP / network drive by one service writing the files, and another service reading them. Perhaps that is still the case in your project? Perhaps someone (from a different company) updated the user the external service is running under? This is an indication that another company changed something that broke your service and didn’t notify your team of that change. How often does that happen? Exception 12.: this might happen when the other side went away for some reason. Backend usually has solid networking so you shouldn’t expect too many of those. On the other hand, this might indicate that a mobile client connecting to the Backend abruptly disconnected. Mobile client disconnecting can be much more frequent. Especially if mobile clients are on a cellular network. Exceptions 13. - 15. are to be expected from time to time and usually become more frequent with increasing load on the RDS. The good news is that they are usually transient. Try to reason through the rest of the exceptions on your own. What else are you experiencing frequently in your project? It does not look like all of the exceptions above should be grouped in the same category: an unknown exception occurred. Yes, those are all unrecoverable exceptions (from the point of view of the outermost try/catch expression). However, that does not mean that nothing can be done about reporting the error.\nHow to improve? To improve the situation we can derive a bit more information about the exception so we can act more meaningfully. It will no longer be an unknown exception. In other words, we translate an exception (and the data it might be carrying) into something more useful. E.g. an error code and an error message intended for a human.\nAssuming you’re using the error model, here is a seed implementation to get you started.\nexception_translation.clj\n(ns my.company.exception-translation (:require [my.company.errors :as errors]) (:import (java.sql SQLException))) (defn translate \"Tries to translate `ex` into something a human might understand. Returns `errors` if it can or `nil` otherwise.\" [ex] (cond (instance? SQLException ex) (condp = (.getSQLState ^SQLException ex) ;; https://www.postgresql.org/docs/11/errcodes-appendix.html \"55P03\" (errors/make-1 {:code :db/lock-timeout}) \"57014\" (errors/make-1 {:code :db/statement-timeout}) nil) ,,, ;; Write more conditions when needed :else nil)) (defn translatable? [ex] (some? (translate ex))) Given that we’re referring to the error message via :code, we also need the error templates.\nresources/error-templates.edn\n:db/lock-timeout \"Another database transaction is in progress. Please try again later.\" :db/statement-timeout \"Database query took too long. This might happen if the system is overloaded. Please try again later.\" Finally, connecting it all in an updated exception middleware. See another post to make sense of the errors namespace used here.\n(defn wrap-exception [handler] (fn [request] (try (handler request) (catch Exception ex (cond ,,, ;; Do you have project specific exceptions above? (exception-translation/translatable? ex) (let [errors (-\u003e\u003e ex (exception-translation/translate) (errors/with-message (get-message-tpls)))] (increment-metric-translated-exception errors) (log-translated-exception errors request) (save-translated-exception-to-db errors request) (respond-to-translated-exception errors)) :else (do (increment-metric-unknown-exception) (log-unknown-exception ex request) (save-to-db ex request) (respond-with-http-500))))))) That’s all it takes. The user of the service should no longer see “Internal Server Error” when a database lock timeout occurs, but rather a more meaningful error message. We can implement logging, metrics, and saving to DB differently too. That means that those exceptions will no longer crowd the list of real unknown exceptions.\nNote that the error messages above should be good enough for other developers, QA, maybe other employees, or service-to-service communication. The messages are probably not good enough for your customers. They won’t know what “database transaction” or “database query” means. If the UI uses the response to show an error to the customer then you might want to change the response message accordingly.\nexception-translation namespace should be highly specific to your project. Don’t just copy/paste what you see above. Use it as an inspiration. If you’re not using the error model then rewrite the code to something that makes sense in your project. Take a look at the exceptions that happen regularly in production and add a line or two to handle them specially.\nThe goal is not to handle every exception you see in the logs! Certainly not something like NullPointerException or ClassCastException. Just the ones that you see frequently and the ones that make sense to your project. A successful application of this principle could be to start with 1-2 exceptions that you see in the logs and expand to a few more cases over time (perhaps months). I have seen from experience that I don’t need to handle a lot of cases, but the ones I do have helped a lot. They especially help with trimming down the noise in the logs.\nWhen it comes to implementing exception-translation namespace any information you can extract is fair game:\nexception type regex matching against the exception message anything that the exception carries: SQL error code, ex-data stack frame nested exceptions That might look very frail, given the JVM differences, OS differences, etc. However, it works quite well in practice. Once written, I didn’t find I needed to update that code constantly to keep it up to date. Quite the contrary.\nIf you want to avoid some of the particularly nasty regexes or looking up the stack frames then a simple trick of wrapping an exception with additional data works quite well. E.g. somewhere in the low-level code.\n(try ... (catch Exception ex (throw (ex-info \"Failed to call service A\" {:calling-service-a? true :request request} ex)))) Of course, if you come to depend on this feature then it pays to write tests for those special cases. You don’t want unit tests here. You want to see how the whole system reacts to a particular exception. So integration or functional tests would be much more useful. For example, take a look at the tests for sql statement and lock timeout.\nI’ll assume there is a central place for the logs. It doesn’t matter where that is: ElasticSearch, Datadog, Sentry, CloudWatch, etc. ↩︎\nPerhaps due to a regulatory reason? ↩︎\n","wordCount":"2027","inLanguage":"en","datePublished":"2023-02-10T12:01:31+01:00","dateModified":"2023-02-10T12:01:31+01:00","author":{"@type":"Person","name":"Miro Bezjak"},"mainEntityOfPage":{"@type":"WebPage","@id":"https://mbezjak.github.io/posts/exception-translation/"},"publisher":{"@type":"Organization","name":"Well Organized Bits","logo":{"@type":"ImageObject","url":"https://mbezjak.github.io/favicon.ico"}}}</script></head><body id=top><script>localStorage.getItem("pref-theme")==="dark"?document.body.classList.add("dark"):localStorage.getItem("pref-theme")==="light"?document.body.classList.remove("dark"):window.matchMedia("(prefers-color-scheme: dark)").matches&&document.body.classList.add("dark")</script><header class=header><nav class=nav><div class=logo><a href=https://mbezjak.github.io accesskey=h title="Well Organized Bits (Alt + H)">Well Organized Bits</a><div class=logo-switches><button id=theme-toggle accesskey=t title="(Alt + T)"><svg id="moon" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg><svg id="sun" xmlns="http://www.w3.org/2000/svg" width="24" height="18" viewBox="0 0 24 24" fill="none" stroke="currentcolor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg></button></div></div><ul id=menu><li><a href=https://mbezjak.github.io/archives/ title=Archive><span>Archive</span></a></li><li><a href=mailto:well.organized.bits@proton.me title=Contact><span>Contact</span></a></li></ul></nav></header><main class=main><article class=post-single><header class=post-header><div class=breadcrumbs><a href=https://mbezjak.github.io>Home</a>&nbsp;»&nbsp;<a href=https://mbezjak.github.io/posts/>Posts</a></div><h1 class=post-title>Exception Translation</h1><div class=post-meta><span title='2023-02-10 12:01:31 +0100 +0100'>February 10, 2023</span>&nbsp;·&nbsp;Miro Bezjak&nbsp;|&nbsp;<a href=https://github.com/mbezjak/mbezjak.github.io/blob/main/content/posts/exception-translation.md rel="noopener noreferrer" target=_blank>Suggest Changes</a></div></header><div class=post-content><p>Can a typical &ldquo;Internal Server Error&rdquo; be improved a bit? Let&rsquo;s find out.</p><p>In fact, let&rsquo;s consider more than just a
<a href=https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500>response</a> that is
typically associated with <em>internal server errors</em>. Those types of errors
usually originate in the outermost <code>try/catch</code> expression. There we might find
code to:</p><ul><li>respond with HTTP status code 500</li><li>increment a metric that an unknown exception occurred</li><li>log the event <sup id=fnref:1><a href=#fn:1 class=footnote-ref role=doc-noteref>1</a></sup></li><li>save the exception to the database <sup id=fnref:2><a href=#fn:2 class=footnote-ref role=doc-noteref>2</a></sup></li><li>etc.</li></ul><p>We&rsquo;ll try to improve everything in the <code>catch</code> block. Just by a little bit.</p><p>It might be a bit easier if we have an example of what we&rsquo;ll target for
improvement. Here it is.</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-clojure data-lang=clojure><span style=display:flex><span>(<span style=color:#66d9ef>defn </span>wrap-exception [handler]
</span></span><span style=display:flex><span>  (<span style=color:#66d9ef>fn </span>[request]
</span></span><span style=display:flex><span>    (<span style=color:#a6e22e>try</span>
</span></span><span style=display:flex><span>      (<span style=color:#a6e22e>handler</span> request)
</span></span><span style=display:flex><span>      (<span style=color:#a6e22e>catch</span> Exception ex
</span></span><span style=display:flex><span>        (<span style=color:#a6e22e>increment-metric-unknown-exception</span>)
</span></span><span style=display:flex><span>        (<span style=color:#a6e22e>log-unknown-exception</span> ex request)
</span></span><span style=display:flex><span>        (<span style=color:#a6e22e>save-to-db</span> ex request)
</span></span><span style=display:flex><span>        (<span style=color:#a6e22e>respond-with-http-500</span>)))))
</span></span></code></pre></div><p>The code above is an example of a <a href=https://github.com/ring-clojure/ring/wiki/Concepts#middleware>ring
middleware</a>. It
doesn&rsquo;t have to be ring, or even HTTP service specific. Any outermost
<code>try/catch</code> expression is relevant for this post:</p><ul><li>when using <code>java.util.concurrent.ExecutorService</code>,</li><li>or spawning new threads in general,</li><li>or using <code>java.lang.Thread.UncaughtExceptionHandler</code>,</li><li>or a <code>try/catch</code> in <code>-main</code> for command line applications,</li><li>etc.</li></ul><h2 id=what-is-there-to-improve>What is there to improve?<a hidden class=anchor aria-hidden=true href=#what-is-there-to-improve>#</a></h2><p>The outermost <code>try/catch</code> expression is all about handling an <strong>unknown</strong>
exception. That is completely fine. After all, it&rsquo;s not possible to anticipate
and/or handle every unforeseen situation.</p><p>However, the way the <code>catch</code> block is usually implemented does have some
drawbacks. At the same time, it&rsquo;s both eliminating too much information and not
accumulating enough information.</p><ul><li>Responding with HTTP 500 is usually collapsing a rich source of information
(stack trace, exception message, any other data the exception is carrying)
into a single error message &ldquo;Something went wrong&rdquo;. That&rsquo;s perhaps too much
reduction of information. There is a lot of middle ground between responding
with a complete stack trace and responding with a generic error message.</li><li>On the other hand, simply dumping all that information as an unknown exception
log event, saving it to DB, or incrementing the same metric is not ideal. That
groups too much into a single category making it harder to deal with.
Extracting a bit more information about the exception might help with
categorization.</li></ul><p>The above is still a bit too abstract. Let&rsquo;s see how those problems might
manifest in the real world: losing users&rsquo; confidence and/or wasting time. What
happens when <em>internal server errors</em> happen a bit too often?</p><p>How would you feel if you saw &ldquo;Internal Server Error&rdquo; too frequently in an app
you need to use? Apart from &ldquo;something didn&rsquo;t work&rdquo;, the error doesn&rsquo;t tell you
much. You&rsquo;d probably be a bit annoyed. Then you&rsquo;d start questioning if the last
thing you did was saved successfully or not. The same thing can happen to any
user of your service: a paying customer, an employee (for internal apps), a
member of the QA team, or other developers if they are consuming your service.
They all can become disheartened because they don&rsquo;t have the necessary
information to conclude something about the error. Is it a real bug or simply
something transient?</p><p>If you&rsquo;re lucky, someone might report a generic error they saw while using the
app. That issue needs to be groomed, planned, and eventually, someone in the
development team needs to spend time debugging it. If the end result is &ldquo;That
was just a DB lock timeout. They should have tried again.&rdquo; then a lot of people
wasted a bunch of time for no good reason. In fact, to &ldquo;save time&rdquo;, someone
might try to shoot down similar issues early on (e.g. in grooming) without doing
the investigation to confirm their assumption. Are you sure that&rsquo;s not a real
bug that was just ignored?</p><p>Even if no new issues enter the Backlog, there is a similar waste happening when
viewing the logs for recent unknown exceptions. Are you mentally filtering out
the &ldquo;I&rsquo;ve seen those exceptions already multiple times&rdquo; from the list of all
logged unknown exceptions? Or maybe you don&rsquo;t feel like looking at the list
anymore because it&rsquo;s mostly stuff you&rsquo;ve seen before.</p><p>This is what we want to avoid. We want the metrics, logs, and errors that the
users see to be a bit more relevant so that when the actual bugs happen,
everyone sees them clearly.</p><h2 id=exception-examples>Exception examples<a hidden class=anchor aria-hidden=true href=#exception-examples>#</a></h2><p>Let&rsquo;s see a couple of exceptions that might end up being caught in the outermost
<code>try/catch</code> expression. If you have access to the production logs, you could
also extract the exception from the last 7 days and consider them as well.</p><ol><li><code>java.lang.NullPointerException</code></li><li><code>java.lang.IllegalArgumentException</code></li><li><code>java.lang.ClassCastException: class java.lang.Long cannot be cast to class clojure.lang.IFn</code></li><li><code>java.net.SocketException: Network is unreachable</code></li><li><code>java.net.SocketTimeoutException: Connect timed out</code></li><li><code>java.net.SocketTimeoutException: Read timed out</code></li><li><code>java.net.ConnectException: Connection refused</code></li><li><code>java.net.UnknownHostException: external-service.com: Name or service not known</code></li><li><code>java.io.FileNotFoundException: /external-service/file-to-import.json (No such file or directory)</code></li><li><code>java.io.FileNotFoundException: /external-service/file-to-import.json (Permission denied)</code></li><li><code>java.io.IOException: Attempted read on closed stream.</code></li><li><code>java.io.IOException: Read error</code></li><li><code>org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout</code></li><li><code>org.postgresql.util.PSQLException: ERROR: canceling statement due to lock timeout Where: while updating tuple (0,1) in relation "users"</code></li><li><code>org.postgresql.util.PSQLException: ERROR: deadlock detected Detail: Process 186 waits for ShareLock on transaction 1140; blocked by process 196. Process 196 waits for ShareLock on transaction 1139; blocked by process 186. Hint: See server log for query details. Where: while updating tuple (0,1) in relation "users"</code></li><li><code>org.postgresql.util.PSQLException: ERROR: new row for relation "users" violates check constraint "users_email_check" Detail: Failing row contains (...).</code></li><li><code>org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey" Detail: Key (id)=(...) already exists.</code></li><li><code>org.postgresql.util.PSQLException: FATAL: sorry, too many clients already</code></li><li><code>org.postgresql.util.PSQLException: Ran out of memory retrieving query results.</code></li><li>etc.</li></ol><p>Are those exceptions all the same? Should they all be handled as unknown
exceptions? Let&rsquo;s reason through a couple of examples and ask ourselves two
questions:</p><ol><li>How unexpected is this exception?</li><li>How frequently do we expect it to occur?</li></ol><p>Answering the questions above:</p><ul><li>Exceptions 1. - 3. and 11. are usually completely unexpected. They represent a
bug in the system. Perhaps a missing <a href=../what-is-a-validation>validation</a> if
not an actual defect. They should not occur frequently. Best if they don&rsquo;t
occur at all.</li><li>Exceptions 4. - 8. might happen if the network becomes unreliable for some
reason. Perhaps someone updated or is currently updating the cloud
infrastructure? How often does someone break the development (or other)
environment in your team?</li><li>Exceptions 9. and 10.: in the old days, files were shared via FTP / network
drive by one service writing the files, and another service reading them.
Perhaps that is still the case in your project? Perhaps someone (from a
different company) updated the user the external service is running under?
This is an indication that another company changed something that broke your
service and didn&rsquo;t notify your team of that change. How often does that
happen?</li><li>Exception 12.: this might happen when the other side went away for some
reason. Backend usually has solid networking so you shouldn&rsquo;t expect too many
of those. On the other hand, this might indicate that a mobile client
connecting to the Backend abruptly disconnected. Mobile client disconnecting
can be much more frequent. Especially if mobile clients are on a cellular
network.</li><li>Exceptions 13. - 15. are to be expected from time to time and usually become
more frequent with increasing load on the RDS. The good news is that they are
usually transient.</li><li>Try to reason through the rest of the exceptions on your own. What else are
you experiencing frequently in your project?</li></ul><p>It does not look like all of the exceptions above should be grouped in the same
category: an unknown exception occurred. Yes, those are all unrecoverable
exceptions (from the point of view of the outermost <code>try/catch</code> expression).
However, that does <strong>not</strong> mean that nothing can be done about reporting the
error.</p><h2 id=how-to-improve>How to improve?<a hidden class=anchor aria-hidden=true href=#how-to-improve>#</a></h2><p>To improve the situation we can derive a bit more information about the
exception so we can act more meaningfully. It will no longer be an unknown
exception. In other words, we translate an exception (and the data it might be
carrying) into something more useful. E.g. an error <code>code</code> and an error
<code>message</code> intended for a human.</p><p>Assuming you&rsquo;re using the <a href=../error-model>error model</a>, here is a seed
implementation to get you started.</p><p><code>exception_translation.clj</code></p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-clojure data-lang=clojure><span style=display:flex><span>(<span style=color:#66d9ef>ns </span>my.company.exception-translation
</span></span><span style=display:flex><span>  (<span style=color:#e6db74>:require</span>
</span></span><span style=display:flex><span>   [my.company.errors <span style=color:#e6db74>:as</span> errors])
</span></span><span style=display:flex><span>  (<span style=color:#e6db74>:import</span>
</span></span><span style=display:flex><span>   (<span style=color:#a6e22e>java.sql</span> SQLException)))
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>(<span style=color:#66d9ef>defn </span>translate
</span></span><span style=display:flex><span>  <span style=color:#e6db74>&#34;Tries to translate `ex` into something a human might understand.
</span></span></span><span style=display:flex><span><span style=color:#e6db74>
</span></span></span><span style=display:flex><span><span style=color:#e6db74>  Returns `errors` if it can or `nil` otherwise.&#34;</span>
</span></span><span style=display:flex><span>  [ex]
</span></span><span style=display:flex><span>  (<span style=color:#a6e22e>cond</span>
</span></span><span style=display:flex><span>    (instance? SQLException ex)
</span></span><span style=display:flex><span>    (<span style=color:#a6e22e>condp</span> = (<span style=color:#a6e22e>.getSQLState</span> <span style=color:#f92672>^</span>SQLException ex)
</span></span><span style=display:flex><span>      <span style=color:#75715e>;; https://www.postgresql.org/docs/11/errcodes-appendix.html</span>
</span></span><span style=display:flex><span>      <span style=color:#e6db74>&#34;55P03&#34;</span> (<span style=color:#a6e22e>errors/make-1</span> {<span style=color:#e6db74>:code</span> <span style=color:#e6db74>:db/lock-timeout</span>})
</span></span><span style=display:flex><span>      <span style=color:#e6db74>&#34;57014&#34;</span> (<span style=color:#a6e22e>errors/make-1</span> {<span style=color:#e6db74>:code</span> <span style=color:#e6db74>:db/statement-timeout</span>})
</span></span><span style=display:flex><span>      nil)
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>    ,,,
</span></span><span style=display:flex><span>    <span style=color:#75715e>;; Write more conditions when needed</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>    <span style=color:#e6db74>:else</span> nil))
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>(<span style=color:#66d9ef>defn </span>translatable? [ex]
</span></span><span style=display:flex><span>  (<span style=color:#a6e22e>some?</span> (<span style=color:#a6e22e>translate</span> ex)))
</span></span></code></pre></div><p>Given that we&rsquo;re referring to the error message via <code>:code</code>, we also need the
<a href=../error-model#code-and-args>error templates</a>.</p><p><code>resources/error-templates.edn</code></p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-clojure data-lang=clojure><span style=display:flex><span><span style=color:#e6db74>:db/lock-timeout</span> <span style=color:#e6db74>&#34;Another database transaction is in progress. Please try again later.&#34;</span>
</span></span><span style=display:flex><span><span style=color:#e6db74>:db/statement-timeout</span> <span style=color:#e6db74>&#34;Database query took too long. This might happen if the system is overloaded. Please try again later.&#34;</span>
</span></span></code></pre></div><p>Finally, connecting it all in an updated exception middleware. See <a href=../using-the-error-model#what-to-do-with-the-errors>another
post</a> to make sense of the
<code>errors</code> namespace used here.</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-clojure data-lang=clojure><span style=display:flex><span>(<span style=color:#66d9ef>defn </span>wrap-exception [handler]
</span></span><span style=display:flex><span>  (<span style=color:#66d9ef>fn </span>[request]
</span></span><span style=display:flex><span>    (<span style=color:#a6e22e>try</span>
</span></span><span style=display:flex><span>      (<span style=color:#a6e22e>handler</span> request)
</span></span><span style=display:flex><span>      (<span style=color:#a6e22e>catch</span> Exception ex
</span></span><span style=display:flex><span>        (<span style=color:#a6e22e>cond</span>
</span></span><span style=display:flex><span>          ,,,
</span></span><span style=display:flex><span>          <span style=color:#75715e>;; Do you have project specific exceptions above?</span>
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>          (<span style=color:#a6e22e>exception-translation/translatable?</span> ex)
</span></span><span style=display:flex><span>          (<span style=color:#66d9ef>let </span>[errors (<span style=color:#a6e22e>-&gt;&gt;</span> ex
</span></span><span style=display:flex><span>                            (<span style=color:#a6e22e>exception-translation/translate</span>)
</span></span><span style=display:flex><span>                            (<span style=color:#a6e22e>errors/with-message</span> (<span style=color:#a6e22e>get-message-tpls</span>)))]
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>increment-metric-translated-exception</span> errors)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>log-translated-exception</span> errors request)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>save-translated-exception-to-db</span> errors request)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>respond-to-translated-exception</span> errors))
</span></span><span style=display:flex><span>
</span></span><span style=display:flex><span>          <span style=color:#e6db74>:else</span>
</span></span><span style=display:flex><span>          (<span style=color:#a6e22e>do</span>
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>increment-metric-unknown-exception</span>)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>log-unknown-exception</span> ex request)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>save-to-db</span> ex request)
</span></span><span style=display:flex><span>            (<span style=color:#a6e22e>respond-with-http-500</span>)))))))
</span></span></code></pre></div><p>That&rsquo;s all it takes. The user of the service should no longer see &ldquo;Internal
Server Error&rdquo; when a database lock timeout occurs, but rather a more meaningful
error message. We can implement logging, metrics, and saving to DB differently
too. That means that those exceptions will no longer crowd the list of real
unknown exceptions.</p><p>Note that the error messages above should be good enough for other developers,
QA, maybe other employees, or service-to-service communication. The messages are
probably not good enough for your customers. They won&rsquo;t know what &ldquo;database
transaction&rdquo; or &ldquo;database query&rdquo; means. If the UI uses the response to show an
error to the customer then you might want to change the response message
accordingly.</p><p><code>exception-translation</code> namespace should be highly specific to your project.
Don&rsquo;t just copy/paste what you see above. Use it as an inspiration. If you&rsquo;re
not using the <a href=../error-model>error model</a> then rewrite the code to something
that makes sense in your project. Take a look at the exceptions that happen
regularly in production and add a line or two to handle them specially.</p><p>The goal is not to handle every exception you see in the logs! Certainly not
something like <code>NullPointerException</code> or <code>ClassCastException</code>. Just the ones
that you see frequently and the ones that make sense to your project. A
successful application of this principle could be to start with 1-2 exceptions
that you see in the logs and expand to a few more cases over time (perhaps
months). I have seen from experience that I don&rsquo;t need to handle a lot of cases,
but the ones I do have helped a lot. They especially help with trimming down the
noise in the logs.</p><p>When it comes to implementing <code>exception-translation</code> namespace any information
you can extract is fair game:</p><ul><li>exception type</li><li>regex matching against the exception message</li><li>anything that the exception carries: SQL error code, <code>ex-data</code></li><li>stack frame</li><li>nested exceptions</li></ul><p>That might look very frail, given the JVM differences, OS differences, etc.
However, it works quite well in practice. Once written, I didn&rsquo;t find I needed
to update that code constantly to keep it up to date. Quite the contrary.</p><p>If you want to avoid some of the particularly nasty regexes or looking up the
stack frames then a simple trick of wrapping an exception with additional data
works quite well. E.g. somewhere in the low-level code.</p><div class=highlight><pre tabindex=0 style=color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4><code class=language-clojure data-lang=clojure><span style=display:flex><span>(<span style=color:#a6e22e>try</span>
</span></span><span style=display:flex><span>  ...
</span></span><span style=display:flex><span>  (<span style=color:#a6e22e>catch</span> Exception ex
</span></span><span style=display:flex><span>    (<span style=color:#a6e22e>throw</span> (<span style=color:#a6e22e>ex-info</span> <span style=color:#e6db74>&#34;Failed to call service A&#34;</span>
</span></span><span style=display:flex><span>                    {<span style=color:#e6db74>:calling-service-a?</span> true
</span></span><span style=display:flex><span>                     <span style=color:#e6db74>:request</span> request}
</span></span><span style=display:flex><span>                    ex))))
</span></span></code></pre></div><p>Of course, if you come to depend on this feature then it pays to write tests for
those special cases. You don&rsquo;t want unit tests here. You want to see how the
whole system reacts to a particular exception. So integration or functional
tests would be much more useful. For example, take a look at the <a href=../integration-tests-for-sql-statement-and-lock-timeout>tests for sql
statement and lock
timeout</a>.</p><div class=footnotes role=doc-endnotes><hr><ol><li id=fn:1><p>I&rsquo;ll assume there is a central place for the logs. It doesn&rsquo;t matter where
that is: ElasticSearch, Datadog, Sentry, CloudWatch, etc.&#160;<a href=#fnref:1 class=footnote-backref role=doc-backlink>&#8617;&#xfe0e;</a></p></li><li id=fn:2><p>Perhaps due to a regulatory reason?&#160;<a href=#fnref:2 class=footnote-backref role=doc-backlink>&#8617;&#xfe0e;</a></p></li></ol></div></div><footer class=post-footer><ul class=post-tags></ul></footer></article></main><footer class=footer><span>&copy; 2023 <a href=https://mbezjak.github.io>Well Organized Bits</a></span>
<span>Powered by
<a href=https://gohugo.io/ rel="noopener noreferrer" target=_blank>Hugo</a> &
        <a href=https://github.com/adityatelange/hugo-PaperMod/ rel=noopener target=_blank>PaperMod</a></span></footer><a href=#top aria-label="go to top" title="Go to Top (Alt + G)" class=top-link id=top-link accesskey=g><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 6" fill="currentcolor"><path d="M12 6H0l6-6z"/></svg></a><script>let menu=document.getElementById("menu");menu&&(menu.scrollLeft=localStorage.getItem("menu-scroll-position"),menu.onscroll=function(){localStorage.setItem("menu-scroll-position",menu.scrollLeft)}),document.querySelectorAll('a[href^="#"]').forEach(e=>{e.addEventListener("click",function(e){e.preventDefault();var t=this.getAttribute("href").substr(1);window.matchMedia("(prefers-reduced-motion: reduce)").matches?document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView():document.querySelector(`[id='${decodeURIComponent(t)}']`).scrollIntoView({behavior:"smooth"}),t==="top"?history.replaceState(null,null," "):history.pushState(null,null,`#${t}`)})})</script><script>var mybutton=document.getElementById("top-link");window.onscroll=function(){document.body.scrollTop>800||document.documentElement.scrollTop>800?(mybutton.style.visibility="visible",mybutton.style.opacity="1"):(mybutton.style.visibility="hidden",mybutton.style.opacity="0")}</script><script>document.getElementById("theme-toggle").addEventListener("click",()=>{document.body.className.includes("dark")?(document.body.classList.remove("dark"),localStorage.setItem("pref-theme","light")):(document.body.classList.add("dark"),localStorage.setItem("pref-theme","dark"))})</script><script>document.querySelectorAll("pre > code").forEach(e=>{const n=e.parentNode.parentNode,t=document.createElement("button");t.classList.add("copy-code"),t.innerHTML="copy";function s(){t.innerHTML="copied!",setTimeout(()=>{t.innerHTML="copy"},2e3)}t.addEventListener("click",t=>{if("clipboard"in navigator){navigator.clipboard.writeText(e.textContent),s();return}const n=document.createRange();n.selectNodeContents(e);const o=window.getSelection();o.removeAllRanges(),o.addRange(n);try{document.execCommand("copy"),s()}catch{}o.removeRange(n)}),n.classList.contains("highlight")?n.appendChild(t):n.parentNode.firstChild==n||(e.parentNode.parentNode.parentNode.parentNode.parentNode.nodeName=="TABLE"?e.parentNode.parentNode.parentNode.parentNode.parentNode.appendChild(t):e.parentNode.appendChild(t))})</script></body></html>